COMPANY_OVERVIEW = {
    "apple": {
        "overview": "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, in Silicon Valley, and known for consumer electronics, software and online services. Founded in 1976 as Apple Computer Company by Steve Jobs, Steve Wozniak and Ronald Wayne, the company was incorporated by Jobs and Wozniak as Apple Computer, Inc. the following year. It was renamed to its current name in 2007 as the company expanded its focus from computers to consumer electronics. Apple is one of the Big Tech companies. The company was founded to market Wozniak's Apple I personal computer. Its successor, the Apple II, became one of the first successful mass-produced microcomputers. Apple introduced the Lisa in 1983 and the Macintosh in 1984 as some of the first computers to use a graphical user interface and a mouse. By 1985, internal conflicts led to Jobs leaving the company to form NeXT and Wozniak withdrawing to other ventures; John Sculley was CEO for over a decade. In the 1990s, Apple lost considerable market share in the PC industry to the lower-priced Wintel duopoly of Intel-powered PC clones running Windows, and neared bankruptcy by 1997.",
        "ceo": "Tim Cook",
        "founded": "Apr 1, 1976",
        "headquarters": "Cupertino, California, United States",
        "website": "https://www.apple.com/",
        "employees": "166000",
    },
    "microsoft": {
        "overview": "Microsoft Corporation is an American multinational technology company headquartered in Redmond, Washington. The company became influential in the rise of personal computers through software like Windows and has since expanded into areas such as Internet services, cloud computing, artificial intelligence, video gaming, and more. A Big Tech company, Microsoft is the largest software company by revenue, one of the most valuable public companies, and one of the most valuable brands globally. Founded in 1975 by Bill Gates and Paul Allen to market BASIC interpreters for the Altair 8800, Microsoft rose to dominate the PC operating system market with MS-DOS in the mid-1980s, followed by Windows. From 1980 to 2021 Microsoft released 9 versions of MS-DOS and 13 versions of Windows. The company's 1986 initial public offering and subsequent rise in its share price created three billionaires and an estimated 12,000 millionaires among Microsoft employees. Since the 1990s, it has increasingly diversified its business. Steve Ballmer replaced Gates as CEO in 2000.",
        "ceo": "Satya Nadella",
        "founded": "Apr 4, 1975",
        "headquarters": "Redmond, Washington, United States",
        "website": "https://www.microsoft.com/",
        "employees": "228000",
    },
    "google": {
        "overview": "Alphabet Inc. is an American multinational technology conglomerate holding company headquartered in Mountain View, California. It was created through a restructuring of Google on October 2, 2015, and became the parent holding company of Google and several former Google subsidiaries. Alphabet is listed on the large-cap section of the Nasdaq under the ticker symbols GOOGL and GOOG; both classes of stock are components of major stock market indices such as the S&P 500 and Nasdaq-100. Alphabet has been described as a Big Tech company. The establishment of Alphabet Inc. was prompted by a desire to make the core Google business 'cleaner and more accountable' while allowing greater autonomy to group companies that operate in businesses other than Internet services. Founders Larry Page and Sergey Brin announced their resignation from their executive posts in December 2019, with the CEO role to be filled by Sundar Pichai, who is also the CEO of Google. Page and Brin remain employees, board members, and controlling shareholders of Alphabet Inc.",
        "ceo": "Sundar Pichai",
        "founded": "Oct 2, 2015",
        "headquarters": "Mountain View, California, United States",
        "website": "https://abc.xyz/",
        "employees": "194668",
    },
    "amazon": {
        "overview": "Amazon.com, Inc. is an American multinational technology company engaged in e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence. Founded in 1994 by Jeff Bezos in Bellevue, Washington, the company originally started as an online marketplace for books but gradually expanded its offerings to include a wide range of product categories, referred to as 'The Everything Store'. Amazon has been described as a Big Tech company. It is mostly known as the world's biggest online shopping retailer and marketplace, best known for a wide range of products and supplying multiple services. Amazon sells books, electronics, pharmacy, car parts, video games, dining, jewelry, food, music, and sports equipment. The company has multiple subsidiaries, including Amazon Web Services, providing cloud computing; Zoox, a self-driving car division; Kuiper Systems, a satellite Internet provider; and Amazon Lab126, a computer hardware R&D provider. Other subsidiaries include Ring, Twitch, IMDb, and Whole Foods Market. Its acquisition of Whole Foods in August 2017 for US$13.4 billion substantially increased its market share and presence as a physical retailer.",
        "ceo": "Andy Jassy",
        "founded": "Jul 5, 1994",
        "headquarters": "Seattle, Washington, United States",
        "website": "https://www.amazon.com/",
        "employees": "1575000",
    },
    "meta": {
        "overview": "Meta Platforms, Inc. is an American multinational technology company headquartered in Menlo Park, California. Meta owns and operates several prominent social media platforms and communication services, including Facebook, Instagram, WhatsApp, Messenger, Threads, and Manus. The company also operates an advertising network for its own sites and third parties; as of 2023, advertising accounted for 97.8 percent of its total revenue. Meta has been described as a part of Big Tech, which refers to the largest six tech companies in the United States, Alphabet, Amazon, Apple, Meta, Microsoft, and Nvidia, which are also the largest companies in the world by market capitalization. The company was originally established in 2004 as TheFacebook, Inc., and was renamed Facebook, Inc. in 2005. In 2021, it rebranded as Meta Platforms, Inc. to reflect a strategic shift toward developing the metaverse—an interconnected digital ecosystem spanning virtual and augmented reality technologies. In 2023, Meta was ranked 31st on the Forbes Global 2000 list of the world's largest public companies.",
        "ceo": "Mark Zuckerberg",
        "founded": "Feb 4, 2004",
        "headquarters": "Menlo Park, California, United States",
        "website": "https://www.meta.com/",
        "employees": "77986",
    },
    "tesla": {
        "overview": "Tesla, Inc. is an American multinational automotive and clean energy company. Headquartered in Austin, Texas, it designs, manufactures, and sells battery electric vehicles, stationary battery energy storage devices from home to grid-scale, solar panels and solar shingles, and related products and services. The company was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning as Tesla Motors. Its name is a tribute to the inventor and electrical engineer Nikola Tesla. In February 2004, Elon Musk led Tesla's first funding round and became the company's chairman, subsequently claiming to be a co-founder; in 2008, he was named chief executive officer. The company began production of its first car model, the Roadster sports car, in 2008; the Model S sedan in 2012; the Model X SUV in 2015; the Model 3 sedan in 2017; the Model Y crossover in 2020; the Tesla Semi truck in 2022; and the Cybertruck pickup truck in 2023. Tesla is one of the world's most valuable companies in terms of market capitalization. Starting in July 2020, it has been the world's most valuable automaker.",
        "ceo": "Elon Musk",
        "founded": "Jul 1, 2003",
        "headquarters": "Austin, Texas, United States",
        "website": "https://www.tesla.com/",
        "employees": "134785",
    },
    "nvidia": {
        "overview": "Nvidia Corporation is an American multinational technology company headquartered in Santa Clara, California. The company develops graphics processing units, systems on chips, and application programming interfaces for data science, high-performance computing, video games, and mobile and automotive applications. Founded in 1993 by Jensen Huang, Chris Malachowsky, and Curtis Priem, Nvidia has been widely described as a Big Tech company. Originally focused on GPUs for video games, Nvidia broadened their use into other markets, including artificial intelligence, professional visualization, and supercomputing. The company's product lines include GeForce GPUs for gaming and creative workloads, and professional GPUs for edge computing, scientific research, and industrial applications. As of the first quarter of 2025, Nvidia held a 92% share of the discrete desktop and laptop GPU market. In the early 2000s, the company invested over a billion dollars to develop CUDA, a software platform and API that enabled GPUs to run massively parallel programs for a broad range of compute-intensive applications.",
        "ceo": "Jensen Huang",
        "founded": "Apr 5, 1993",
        "headquarters": "Santa Clara, California, United States",
        "website": "https://www.nvidia.com/",
        "employees": "42000",
    },
}
